export const template =
`
<section
	aria-live='polite'
	ref="player-viewport"
	tabindex="0"
>
<form
	ref="form"
	autocomplete="off"
	@submit.prevent="onSubmit"
	@change="onChangeDoSubmit"
>
<scene-viewport
	v-bind:key="activity.id"
	id="player-scene"
	ref="scene"
	v-if="isSceneable"
	:value="scene"
>
</scene-viewport>
</form>
<b-container
	v-if="shouldClickToContinue"
	aria-disabled="!shouldClickToContinue"
	aria-controls="player-scene"
	aria-live="polite"
>
	<b-row>
		<b-col
			class="d-flex"
		>
			<b-button
				class="m-auto w-50"
				v-on:click="onInput( 'click', $event )"
				v-t="'shared.label-continue'"
			></b-button>
		</b-col>
	</b-row>
</b-container>
</section>
`;